<?php
/**
 * Zaproo Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Zaproo does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Zaproo does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Zaproo
 * @package    Esto_HirePurchase
 * @version    1.0.2
 * @copyright  Copyright (c) Zaproo Co. (http://www.zaproo.com)
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div><?= __('Your order #%1 has been canceled.', $block->getOrderId()) ?></div>
<div><?= __('You will be redirected to the main page in 5 seconds.') ?></div>

<script>
    require(['jquery'], function ($) {
        $(function () {
            setTimeout(function () {
                window.location.assign('/');
            }, 5000);
        });
    });
</script>
